/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Samantha
 */
public class ventanaAsignarAdministradores extends javax.swing.JInternalFrame {

    /**
     * Creates new form ventanaAsignarAdministradores
     */
    public ventanaAsignarAdministradores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVentanaAsignarAdministradores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonas = new javax.swing.JTable();
        scrollBarVentanaAsignarAdministradores = new javax.swing.JScrollBar();
        lblTituloAsignarAdministradores = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        panelVentanaAsignarAdministradores.setBackground(new java.awt.Color(190, 160, 100));
        panelVentanaAsignarAdministradores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaPersonas.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tablaPersonas.setForeground(new java.awt.Color(240, 240, 240));
        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Persona", "Administrador", "Administrador Master"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPersonas);

        panelVentanaAsignarAdministradores.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 580, -1));
        panelVentanaAsignarAdministradores.add(scrollBarVentanaAsignarAdministradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 0, 20, 330));

        lblTituloAsignarAdministradores.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTituloAsignarAdministradores.setText("Asignar Administradores");
        panelVentanaAsignarAdministradores.add(lblTituloAsignarAdministradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/reporte.png"))); // NOI18N
        panelVentanaAsignarAdministradores.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentanaAsignarAdministradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentanaAsignarAdministradores, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloAsignarAdministradores;
    private javax.swing.JPanel panelVentanaAsignarAdministradores;
    private javax.swing.JScrollBar scrollBarVentanaAsignarAdministradores;
    private javax.swing.JTable tablaPersonas;
    // End of variables declaration//GEN-END:variables
}
