/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Samantha
 */
public class ventanaCrearUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form ventanaCrearUsuario
     */
    public ventanaCrearUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearUsuario = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        lblApellido2 = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        fieldNombre = new javax.swing.JTextField();
        fieldApellido2 = new javax.swing.JTextField();
        fieldTelefono = new javax.swing.JTextField();
        fieldApellido1 = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        field_ID = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Crear Usuario Nuevo - Estimacao");

        panelCrearUsuario.setBackground(new java.awt.Color(190, 160, 100));
        panelCrearUsuario.setToolTipText("");

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(170, 80, 0));
        lblNombre.setText("Nombre");

        lblApellido1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblApellido1.setForeground(new java.awt.Color(170, 80, 0));
        lblApellido1.setText("Primer      Apellido");

        lblApellido2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblApellido2.setForeground(new java.awt.Color(170, 80, 0));
        lblApellido2.setText("Segundo Apellido");

        lblTelefono.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(170, 80, 0));
        lblTelefono.setText("Teléfono");

        lblEmail.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(170, 80, 0));
        lblEmail.setText("E-mail");

        lblid.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblid.setForeground(new java.awt.Color(170, 80, 0));
        lblid.setText("ID (Sólo números)");

        lblPassword.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(170, 80, 0));
        lblPassword.setText("Password");

        btnCrear.setBackground(new java.awt.Color(255, 153, 0));
        btnCrear.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(170, 80, 0));
        btnCrear.setText("Crear");

        fieldNombre.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        fieldNombre.setToolTipText("");
        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });

        fieldApellido2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        fieldApellido2.setToolTipText("");

        fieldTelefono.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        fieldTelefono.setToolTipText("");

        fieldApellido1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        fieldApellido1.setToolTipText("");

        fieldEmail.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        fieldEmail.setToolTipText("");

        field_ID.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        field_ID.setToolTipText("");

        fieldPassword.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        fieldPassword.setToolTipText("");

        javax.swing.GroupLayout panelCrearUsuarioLayout = new javax.swing.GroupLayout(panelCrearUsuario);
        panelCrearUsuario.setLayout(panelCrearUsuarioLayout);
        panelCrearUsuarioLayout.setHorizontalGroup(
            panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearUsuarioLayout.createSequentialGroup()
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearUsuarioLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCrearUsuarioLayout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addGap(70, 70, 70)
                                .addComponent(fieldNombre))
                            .addGroup(panelCrearUsuarioLayout.createSequentialGroup()
                                .addComponent(lblApellido2)
                                .addGap(17, 17, 17)
                                .addComponent(fieldApellido2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                            .addGroup(panelCrearUsuarioLayout.createSequentialGroup()
                                .addComponent(lblTelefono)
                                .addGap(67, 67, 67)
                                .addComponent(fieldTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                            .addGroup(panelCrearUsuarioLayout.createSequentialGroup()
                                .addComponent(lblApellido1)
                                .addGap(16, 16, 16)
                                .addComponent(fieldApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                            .addGroup(panelCrearUsuarioLayout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addGap(80, 80, 80)
                                .addComponent(fieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                            .addGroup(panelCrearUsuarioLayout.createSequentialGroup()
                                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblid)
                                    .addComponent(lblPassword))
                                .addGap(20, 20, 20)
                                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(field_ID)
                                    .addComponent(fieldPassword)))))
                    .addGroup(panelCrearUsuarioLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnCrear)))
                .addContainerGap())
        );
        panelCrearUsuarioLayout.setVerticalGroup(
            panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearUsuarioLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido1)
                    .addComponent(fieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellido2)
                    .addComponent(fieldApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(fieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblid)
                    .addComponent(field_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCrear)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JTextField fieldApellido1;
    private javax.swing.JTextField fieldApellido2;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldPassword;
    private javax.swing.JTextField fieldTelefono;
    private javax.swing.JTextField field_ID;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblid;
    private javax.swing.JPanel panelCrearUsuario;
    // End of variables declaration//GEN-END:variables
}
