/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Samantha
 */
public class VentanaCrearUsuario extends javax.swing.JInternalFrame {

    private static VentanaCrearUsuario miVentanaCrearUsuario;
    
    /**
     * Creates new form ventanaCrearUsuario
     */
    private VentanaCrearUsuario() {
        initComponents();
    }
    
    public static VentanaCrearUsuario getInstance()
    {
        if(miVentanaCrearUsuario == null)
        {
            miVentanaCrearUsuario = new VentanaCrearUsuario();
        }
        return miVentanaCrearUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearUsuario = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        lblApellido2 = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        fieldNombre = new javax.swing.JTextField();
        fieldApellido2 = new javax.swing.JTextField();
        fieldTelefono = new javax.swing.JTextField();
        fieldApellido1 = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        field_ID = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JTextField();
        lblimagenUsuario = new javax.swing.JLabel();
        lblimagenAdoptante = new javax.swing.JLabel();
        lblCuna = new javax.swing.JLabel();
        checkAdoptante = new javax.swing.JCheckBox();
        checkCasaCuna = new javax.swing.JCheckBox();
        btnCancelar = new javax.swing.JButton();
        lblUbicacion = new javax.swing.JLabel();
        lblTipoResidencia = new javax.swing.JLabel();
        fieldUbicacion = new javax.swing.JTextField();
        fieldTipoResidencia = new javax.swing.JTextField();
        lblTamano = new javax.swing.JLabel();
        lblCantidadMascotas = new javax.swing.JLabel();
        boxEspecie = new javax.swing.JComboBox();
        boxTamaño = new javax.swing.JComboBox();
        lblTamano1 = new javax.swing.JLabel();
        boxDonacion = new javax.swing.JComboBox();
        checkDonacion = new javax.swing.JCheckBox();
        lblEspecie = new javax.swing.JLabel();
        boxCantidadMascotas = new javax.swing.JComboBox();
        fieldNickname = new javax.swing.JTextField();
        lblNickname = new javax.swing.JLabel();

        setIconifiable(true);
        setTitle("Crear Usuario Nuevo - Estimação");

        panelCrearUsuario.setBackground(new java.awt.Color(190, 160, 100));
        panelCrearUsuario.setToolTipText("");
        panelCrearUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblNombre.setText("Nombre");
        panelCrearUsuario.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lblApellido1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblApellido1.setText("Primer      Apellido");
        panelCrearUsuario.add(lblApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        lblApellido2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblApellido2.setText("Segundo Apellido");
        panelCrearUsuario.add(lblApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblTelefono.setText("Teléfono");
        panelCrearUsuario.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        lblEmail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblEmail.setText("E-mail");
        panelCrearUsuario.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        lblid.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblid.setText("Cédula ");
        panelCrearUsuario.add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        lblPassword.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblPassword.setText("Password");
        panelCrearUsuario.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        btnCrear.setBackground(new java.awt.Color(255, 153, 0));
        btnCrear.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(170, 80, 0));
        btnCrear.setText("Crear");
        panelCrearUsuario.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 110, 50));

        fieldNombre.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        fieldNombre.setToolTipText("");
        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });
        panelCrearUsuario.add(fieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 204, -1));

        fieldApellido2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        fieldApellido2.setToolTipText("");
        panelCrearUsuario.add(fieldApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 204, -1));

        fieldTelefono.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        fieldTelefono.setToolTipText("");
        panelCrearUsuario.add(fieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 205, -1));

        fieldApellido1.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        fieldApellido1.setToolTipText("");
        panelCrearUsuario.add(fieldApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 204, -1));

        fieldEmail.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        fieldEmail.setToolTipText("");
        panelCrearUsuario.add(fieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 204, -1));

        field_ID.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        field_ID.setToolTipText("");
        field_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_IDActionPerformed(evt);
            }
        });
        panelCrearUsuario.add(field_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 204, -1));

        fieldPassword.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        fieldPassword.setToolTipText("");
        panelCrearUsuario.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 204, -1));

        lblimagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario.png"))); // NOI18N
        panelCrearUsuario.add(lblimagenUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 70, 80));

        lblimagenAdoptante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/adoptar.png"))); // NOI18N
        panelCrearUsuario.add(lblimagenAdoptante, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        lblCuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/casaCuna.png"))); // NOI18N
        panelCrearUsuario.add(lblCuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 30, 140, -1));

        checkAdoptante.setBackground(new java.awt.Color(190, 160, 100));
        checkAdoptante.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        checkAdoptante.setText("Adoptante");
        panelCrearUsuario.add(checkAdoptante, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 173, -1, -1));

        checkCasaCuna.setBackground(new java.awt.Color(190, 160, 100));
        checkCasaCuna.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        checkCasaCuna.setText("Casa Cuna");
        panelCrearUsuario.add(checkCasaCuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 153, 0));
        btnCancelar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(170, 80, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(63, 23));
        btnCancelar.setMinimumSize(new java.awt.Dimension(63, 23));
        btnCancelar.setPreferredSize(new java.awt.Dimension(63, 23));
        panelCrearUsuario.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 100, 50));

        lblUbicacion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblUbicacion.setText("Ubicación");
        panelCrearUsuario.add(lblUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        lblTipoResidencia.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblTipoResidencia.setText("Tipo de Residencia");
        panelCrearUsuario.add(lblTipoResidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        fieldUbicacion.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        fieldUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUbicacionActionPerformed(evt);
            }
        });
        panelCrearUsuario.add(fieldUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 160, -1));

        fieldTipoResidencia.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        fieldTipoResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTipoResidenciaActionPerformed(evt);
            }
        });
        panelCrearUsuario.add(fieldTipoResidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 160, -1));

        lblTamano.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblTamano.setText("Donación");
        panelCrearUsuario.add(lblTamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));

        lblCantidadMascotas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblCantidadMascotas.setText("Cantidad de Mascotas");
        panelCrearUsuario.add(lblCantidadMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, -1));

        boxEspecie.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        boxEspecie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Perro", "Gato", "Pájaro", "Tortuga", "Roedor Pequeño", "Conejo" }));
        panelCrearUsuario.add(boxEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 110, -1));

        boxTamaño.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        boxTamaño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Menor a 20cm", "De 20cm a 50cm", "De 50cm a 80cm", "Mayor a 1m" }));
        panelCrearUsuario.add(boxTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 110, -1));

        lblTamano1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblTamano1.setText("Tamaño");
        panelCrearUsuario.add(lblTamano1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, -1, -1));

        boxDonacion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        boxDonacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comida", "Shampoo", "Talco", "Medicamentos", "Pulgicidas", "Dinero" }));
        panelCrearUsuario.add(boxDonacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 110, -1));

        checkDonacion.setBackground(new java.awt.Color(190, 160, 100));
        checkDonacion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        checkDonacion.setText("Recibir Donaciones");
        checkDonacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDonacionActionPerformed(evt);
            }
        });
        panelCrearUsuario.add(checkDonacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));

        lblEspecie.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblEspecie.setText("Especie");
        panelCrearUsuario.add(lblEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        boxCantidadMascotas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        boxCantidadMascotas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        panelCrearUsuario.add(boxCantidadMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, 40, -1));

        fieldNickname.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        fieldNickname.setToolTipText("");
        panelCrearUsuario.add(fieldNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 204, -1));

        lblNickname.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblNickname.setText("Nickname");
        panelCrearUsuario.add(lblNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void field_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_IDActionPerformed

    private void fieldUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUbicacionActionPerformed

    private void fieldTipoResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTipoResidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTipoResidenciaActionPerformed

    private void checkDonacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDonacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkDonacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxCantidadMascotas;
    private javax.swing.JComboBox boxDonacion;
    private javax.swing.JComboBox boxEspecie;
    private javax.swing.JComboBox boxTamaño;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JCheckBox checkAdoptante;
    private javax.swing.JCheckBox checkCasaCuna;
    private javax.swing.JCheckBox checkDonacion;
    private javax.swing.JTextField fieldApellido1;
    private javax.swing.JTextField fieldApellido2;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldNickname;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldPassword;
    private javax.swing.JTextField fieldTelefono;
    private javax.swing.JTextField fieldTipoResidencia;
    private javax.swing.JTextField fieldUbicacion;
    private javax.swing.JTextField field_ID;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblCantidadMascotas;
    private javax.swing.JLabel lblCuna;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEspecie;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTamano;
    private javax.swing.JLabel lblTamano1;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoResidencia;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblimagenAdoptante;
    private javax.swing.JLabel lblimagenUsuario;
    private javax.swing.JPanel panelCrearUsuario;
    // End of variables declaration//GEN-END:variables
}
