/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controladores.ControladorDonaciones;
import Interfaces.IConstantes;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Samantha
 */
public class VentanaInscribirAsociacion extends javax.swing.JInternalFrame implements  IConstantes
{

    private static VentanaInscribirAsociacion miVentanaCrearUsuario;
    
    /**
     * Creates new form ventanaCrearUsuario
     */
    private VentanaInscribirAsociacion() 
    {
        initComponents();
    }
    
    public static VentanaInscribirAsociacion getInstance()
    {
        if(miVentanaCrearUsuario == null)
        {
            miVentanaCrearUsuario = new VentanaInscribirAsociacion();
        }
        return miVentanaCrearUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrearUsuario = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblRazonSocial = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        btnInscribir = new javax.swing.JButton();
        fieldNombre = new javax.swing.JTextField();
        fieldTelefono = new javax.swing.JTextField();
        fieldRazonSocial = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        field_ID = new javax.swing.JTextField();
        lblimagenAdoptante = new javax.swing.JLabel();
        checkCasaCuna = new javax.swing.JCheckBox();
        btnCerrar = new javax.swing.JButton();
        checkDonacion = new javax.swing.JCheckBox();
        lblDireccion = new javax.swing.JLabel();
        fieldDireccion = new javax.swing.JTextField();

        setIconifiable(true);
        setTitle("Inscribir Asociación - Estimação");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logoE.png"))); // NOI18N

        panelCrearUsuario.setBackground(new java.awt.Color(190, 160, 100));
        panelCrearUsuario.setToolTipText("");
        panelCrearUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblNombre.setText("Nombre Comercial");
        panelCrearUsuario.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, -1));

        lblRazonSocial.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblRazonSocial.setText("Razón Social");
        panelCrearUsuario.add(lblRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblTelefono.setText("Teléfono");
        panelCrearUsuario.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        lblEmail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblEmail.setText("Sitio Web / Email");
        panelCrearUsuario.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, -1));

        lblid.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblid.setText("Cédula Jurídica");
        panelCrearUsuario.add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        btnInscribir.setBackground(new java.awt.Color(255, 153, 0));
        btnInscribir.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnInscribir.setForeground(new java.awt.Color(170, 80, 0));
        btnInscribir.setText("Inscribir");
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });
        panelCrearUsuario.add(btnInscribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 110, 50));

        fieldNombre.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        fieldNombre.setToolTipText("");
        panelCrearUsuario.add(fieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 204, -1));

        fieldTelefono.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        fieldTelefono.setToolTipText("");
        fieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldTelefonoKeyTyped(evt);
            }
        });
        panelCrearUsuario.add(fieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 205, -1));

        fieldRazonSocial.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        fieldRazonSocial.setToolTipText("");
        panelCrearUsuario.add(fieldRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 204, -1));

        fieldEmail.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        fieldEmail.setToolTipText("");
        panelCrearUsuario.add(fieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 204, -1));

        field_ID.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        field_ID.setToolTipText("");
        field_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field_IDKeyTyped(evt);
            }
        });
        panelCrearUsuario.add(field_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 204, -1));

        lblimagenAdoptante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/adoptar.png"))); // NOI18N
        panelCrearUsuario.add(lblimagenAdoptante, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 120, 130));

        checkCasaCuna.setBackground(new java.awt.Color(190, 160, 100));
        checkCasaCuna.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        checkCasaCuna.setSelected(true);
        checkCasaCuna.setText("Asociacion en Pro del cuido de los animales");
        checkCasaCuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCasaCunaActionPerformed(evt);
            }
        });
        panelCrearUsuario.add(checkCasaCuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        btnCerrar.setBackground(new java.awt.Color(255, 153, 0));
        btnCerrar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(170, 80, 0));
        btnCerrar.setText("Cerrar");
        btnCerrar.setMaximumSize(new java.awt.Dimension(63, 23));
        btnCerrar.setMinimumSize(new java.awt.Dimension(63, 23));
        btnCerrar.setPreferredSize(new java.awt.Dimension(63, 23));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        panelCrearUsuario.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 100, 50));

        checkDonacion.setBackground(new java.awt.Color(190, 160, 100));
        checkDonacion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        checkDonacion.setText("Recibir Donaciones");
        checkDonacion.setEnabled(false);
        panelCrearUsuario.add(checkDonacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        lblDireccion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblDireccion.setText("Dirección");
        panelCrearUsuario.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        fieldDireccion.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        fieldDireccion.setToolTipText("");
        fieldDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldDireccionKeyTyped(evt);
            }
        });
        panelCrearUsuario.add(fieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 204, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        //(String nombre, String razonSocial, String telefono, String sitioWeb, String cedula, String direccion)
        ControladorDonaciones.getInstance().inscribirAsociaciones(fieldNombre.getText(),
                fieldRazonSocial.getText(), fieldTelefono.getText(), fieldEmail.getText(), field_ID.getText(), fieldDireccion.getText());      
        JOptionPane.showMessageDialog(null, "Asociación agregada con éxito");
        btnCerrarActionPerformed(evt);
        
    }//GEN-LAST:event_btnInscribirActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
    checkCasaCuna.setSelected(false);
    checkDonacion.setSelected(false);
    fieldRazonSocial.setText("");
    fieldEmail.setText("");
    fieldNombre.setText("");
    fieldTelefono.setText("");
    field_ID.setText("");
    this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void checkCasaCunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCasaCunaActionPerformed
        if(checkCasaCuna.isSelected()){
            activarDonacion();
        }
    }//GEN-LAST:event_checkCasaCunaActionPerformed

    private void fieldTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldTelefonoKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese Solo Numeros en este espacio");
        }
    }//GEN-LAST:event_fieldTelefonoKeyTyped

    private void field_IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_IDKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese Solo Numeros en este espacio");
        }
    }//GEN-LAST:event_field_IDKeyTyped

    private void fieldDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldDireccionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDireccionKeyTyped


    private void activarDonacion()
    {
        if(checkCasaCuna.isSelected())
        {
            checkDonacion.setEnabled(true);
        }
        else
        {
            checkDonacion.setEnabled(false);
            checkDonacion.setSelected(false);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JCheckBox checkCasaCuna;
    private javax.swing.JCheckBox checkDonacion;
    private javax.swing.JTextField fieldDireccion;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldRazonSocial;
    private javax.swing.JTextField fieldTelefono;
    private javax.swing.JTextField field_ID;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblimagenAdoptante;
    private javax.swing.JPanel panelCrearUsuario;
    // End of variables declaration//GEN-END:variables
}
