/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author Samantha
 */
public class VentanaAcercade extends javax.swing.JInternalFrame {

    private static VentanaAcercade miVentanaAcercade;
    
    /**
     * Creates new form ventanaAcercade
     */
    private VentanaAcercade() 
    {
        initComponents();
    }
    
    public static VentanaAcercade getInstance()
    {
        if(miVentanaAcercade == null)
        {
            miVentanaAcercade = new VentanaAcercade();
        }
        return miVentanaAcercade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAcercade = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUniversidad = new javax.swing.JLabel();
        lblClick = new javax.swing.JLabel();
        lblAcceder = new javax.swing.JLabel();
        lblHipervinculo = new javax.swing.JLabel();
        lblCreadorPor = new javax.swing.JLabel();
        lblNombreAdrian = new javax.swing.JLabel();
        lblNombreFede = new javax.swing.JLabel();
        lblNombreMarco = new javax.swing.JLabel();
        lblNombreSamy = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Acerca de Estimação");
        setVisible(false);

        panelAcercade.setBackground(new java.awt.Color(190, 160, 100));
        panelAcercade.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logoE.png"))); // NOI18N
        panelAcercade.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblUniversidad.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUniversidad.setText("Instituto Tecnológico de Costa Rica");
        panelAcercade.add(lblUniversidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        lblClick.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblClick.setText("CLICK");
        panelAcercade.add(lblClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        lblAcceder.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblAcceder.setText("Accede al manual de Usuario");
        panelAcercade.add(lblAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        lblHipervinculo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblHipervinculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/web.png"))); // NOI18N
        lblHipervinculo.setText("AQUÍ");
        lblHipervinculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                irWeb(evt);
            }
        });
        panelAcercade.add(lblHipervinculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 60, 110, -1));

        lblCreadorPor.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCreadorPor.setText("Creado por");
        panelAcercade.add(lblCreadorPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        lblNombreAdrian.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNombreAdrian.setText("Adrián Soto Loría");
        panelAcercade.add(lblNombreAdrian, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        lblNombreFede.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNombreFede.setText("Federico Montealegre C.");
        panelAcercade.add(lblNombreFede, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        lblNombreMarco.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNombreMarco.setText("Marco Soto Morera");
        panelAcercade.add(lblNombreMarco, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        lblNombreSamy.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNombreSamy.setText("Samantha Arburola León");
        panelAcercade.add(lblNombreSamy, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        lblCarrera.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCarrera.setText("Ingeniería en Computación");
        panelAcercade.add(lblCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTitulo.setText("Estimação");
        panelAcercade.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAcercade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAcercade, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void irWeb(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_irWeb
        try {
        if (Desktop.isDesktopSupported()) {
        Desktop desktop = Desktop.getDesktop();
        if (desktop.isSupported(Desktop.Action.BROWSE)) {
        desktop.browse(new URI("http://samarburola.wix.com/estimacao"));
        }
        }
        } catch (Exception e) {
        e.printStackTrace();
        }        
    }//GEN-LAST:event_irWeb


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAcceder;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblClick;
    private javax.swing.JLabel lblCreadorPor;
    private javax.swing.JLabel lblHipervinculo;
    private javax.swing.JLabel lblNombreAdrian;
    private javax.swing.JLabel lblNombreFede;
    private javax.swing.JLabel lblNombreMarco;
    private javax.swing.JLabel lblNombreSamy;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUniversidad;
    private javax.swing.JPanel panelAcercade;
    // End of variables declaration//GEN-END:variables
}
